#Partie Rappel!!





---



---

#Numpy

In [1]:
import numpy as np

In [2]:
x = np.array([[1,2.5,4,5], [14,7,4,5],[5,4,5,2]], dtype = float)

In [10]:
x


array([[ 1. ,  2.5,  4. ,  5. ],
       [14. ,  7. ,  4. ,  5. ],
       [ 5. ,  4. ,  5. ,  2. ]])

In [11]:
x.ndim

2

In [12]:
a = np.array([1,2,3])

In [13]:
a.ndim

1

In [14]:
a.shape

(3,)

In [17]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

#The basics!!!!!

In [35]:
a = np.array([1.2,"2",3],dtype=float)

In [36]:
a

array([1.2, 2. , 3. ])

In [20]:
b = np.array([[[9,8,7,4],[6,5,4,6],[6,5,4,6]],
               
              [[19,18,17,14],[6,5,4,6],[6,5,4,6]],
              
              [[9,8,7,4],[6,5,4,6],[6,5,4,6]]
              ])


In [24]:
b.ndim

3

In [25]:
b

array([[[ 9,  8,  7,  4],
        [ 6,  5,  4,  6],
        [ 6,  5,  4,  6]],

       [[19, 18, 17, 14],
        [ 6,  5,  4,  6],
        [ 6,  5,  4,  6]],

       [[ 9,  8,  7,  4],
        [ 6,  5,  4,  6],
        [ 6,  5,  4,  6]]])

In [22]:
b.shape# num de : dim, number ligne, number of colomns

(3, 3, 4)

In [26]:
x = np.array([[1,2,3],
              [14,15,1]])

In [27]:
x.shape  #num de ligne et colonne

(2, 3)

In [28]:
x.ndim

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.size #nombre de ligne * nombre de colonne

6


#Accessing/Changing specific elements

In [ ]:
x

array([[ 1,  2,  3],
       [14, 15,  1]])

In [30]:
x[:,:2]

array([[ 1,  2],
       [14, 15]])

In [39]:
x[1,2]

1

In [40]:
x = np.array([[1,22,8,4],
              [4,15,10,7]])

In [41]:
x[:,2]

array([ 8, 10])

In [42]:
x[1,1:3]

array([15, 10])

In [43]:
x = np.array([[1,22,8,4,9,27,8],
              [4,15,10,7,19,12,18]])
x

array([[ 1, 22,  8,  4,  9, 27,  8],
       [ 4, 15, 10,  7, 19, 12, 18]])

In [44]:
x[(x< 12) & (x>7)]

array([ 8,  9,  8, 10])

In [45]:
x

array([[ 1, 22,  8,  4,  9, 27,  8],
       [ 4, 15, 10,  7, 19, 12, 18]])

In [47]:
# [startindex:endindex:stepsize]
x[:, 1:-1:1]

array([[22,  8,  4,  9, 27],
       [15, 10,  7, 19, 12]])

In [48]:
x[:,2]

array([ 8, 10])

In [49]:
x = 333333333333
x

333333333333

In [57]:
x

333333333333

#Initialization of an array !!

In [64]:
d1 = np.ones((2,3),dtype=int) +98
d1

array([[99, 99, 99],
       [99, 99, 99]])

In [61]:
d2 = np.ones((2,3),dtype=float) + 7

In [65]:
d1[1,2] = 17 *5
d1

array([[99, 99, 99],
       [99, 99, 85]])

In [70]:
array1 = np.array([1,2,3,4])
array2 = np.array([4,5,6,7])

In [71]:
array1 * array2 

array([ 4, 10, 18, 28])

In [75]:
np.full((2,4),'100000007')


array([['100000007', '100000007', '100000007', '100000007'],
       ['100000007', '100000007', '100000007', '100000007']], dtype='<U9')

In [76]:
c= np.full((2,3),7)
c

array([[7, 7, 7],
       [7, 7, 7]])

In [77]:
np.full_like(c, 9) #c c'est notre matrice 

array([[9, 9, 9],
       [9, 9, 9]])

In [78]:

# Random decimal numbers
np.random.rand(4,2)

array([[0.34088457, 0.78007066],
       [0.46702651, 0.34781282],
       [0.2500854 , 0.24881915],
       [0.01075222, 0.85814785]])

In [79]:
np.random.randint(-4,8, size=(3,3)) #des valeurs entre -4 et 8,  avec la taille 3*3

array([[ 0,  2,  3],
       [ 1, -3,  1],
       [ 2,  2,  4]])

In [80]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
arr = np.array([[1,2,3,-2,0,11,15,9]])
arr[(arr > 0) & (arr < 10)] 

array([1, 2, 3, 9])

In [82]:
arr[(arr <2) & (arr<10)]

array([ 1, -2,  0])


# NumPy exercises


In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.22.4


In [84]:
reshaping = np.array([1,2,3,4,5,6])
reshaping

array([1, 2, 3, 4, 5, 6])

In [85]:
reshaping.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
liste = list(reshaping)
liste

[1, 2, 3, 4, 5, 6]

In [88]:
type(liste)

list

In [91]:
array3 = np.array(liste)
array3

array([1, 2, 3, 4, 5, 6])

In [90]:
type(array3)

numpy.ndarray

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [95]:
from numpy.core.numeric import full_like
# your code goes here
x=np.full((10),0)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])



### Create a numpy array with values ranging from 10 to 49

In [99]:
np.random.randint(10,49, size=(3,3))

array([[40, 17, 34],
       [16, 26, 16],
       [39, 13, 47]])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [101]:
d= np.ones((2,2),dtype=int)
d


array([[1, 1],
       [1, 1]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [103]:
# your code goes here
d2 = np.ones((3,2),dtype=int)
d2

array([[1, 1],
       [1, 1],
       [1, 1]])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

Exemple : https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html

In [107]:
# your code goes here
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [108]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])



### Create a numpy matrix of 4*4 integers, filled with fives.

https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-13.php 


In [111]:
# your code goes here
d3 = np.ones((4,4),dtype=int)*5
d3

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [112]:
# your code goes here

d4=np.full_like(d3, 9)
d4

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])



### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [114]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [118]:
# your code goes here
np.random.randint(1,4, size=(3,3),dtype=int)

array([[1, 1, 3],
       [1, 1, 2],
       [1, 3, 3]])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [128]:
# your code goes here
np.random.rand(3,3,3)

array([[[0.21499297, 0.77809483, 0.22158247],
        [0.47758741, 0.87504498, 0.43125457],
        [0.7060415 , 0.24297808, 0.27761147]],

       [[0.57637756, 0.10389368, 0.6857442 ],
        [0.12250492, 0.85571018, 0.9080414 ],
        [0.15417121, 0.2532128 , 0.62628625]],

       [[0.06200327, 0.97034393, 0.75775475],
        [0.51121231, 0.7844228 , 0.35522231],
        [0.87467298, 0.52693026, 0.02490698]]])



### Given the X python list convert it to an Y numpy array

In [133]:
# your code goes here
X=[5,3,2,1,2,2]
X=np.array(X).reshape(3,2)
X

array([[5, 3],
       [2, 1],
       [2, 2]])



### Given the X numpy array, make a copy and store it on Y.

In [137]:
# your code goes here
Y=X.copy()
Y

array([[5, 3],
       [2, 1],
       [2, 2]])

In [138]:
X

array([[5, 3],
       [2, 1],
       [2, 2]])



### Create a numpy array with numbers from 1 to 10

In [141]:
# your code goes here
y=np.random.randint(1,10,size=(1,10))
y

array([[2, 5, 6, 7, 6, 3, 2, 7, 5, 2]])



### Create a numpy array with the odd numbers between 1 to 10

In [145]:
# your code goes here
y=np.arange(1,11)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])



### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [152]:
# your code goes here
r=np.arange(9)
r.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



### Show the memory size of the given Z numpy matrix

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [9]:
# your code goes here
x=np.array([1,2,3,4,5,6,7,8,9])
x[0]

1



### Given the X numpy array, show it's last element

In [10]:
# your code goes here
x[-1]

9



### Given the X numpy array, show it's first three elements

In [11]:
# your code goes here
x[:3]

array([1, 2, 3])



---



### Create a numpy array with numbers from 1 to 10, in descending order.

In [17]:
# your code goes here
#" https://www.kite.com/python/answers/how-to-sort-a-numpy-array-in-descending-order-in-python
x[::-1].sort()
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1])



### Given the X numpy array, show all middle elements

In [20]:

X = np.array([1, 2, 3, 4, 5, 6])
if len(X) % 2 == 0:
    middle1 = X[len(X)//2 - 1]
    middle2 = X[len(X)//2]
    print("Middle elements:", middle1, middle2)
else:
    middle = X[len(X)//2]
    print("Middle element:", middle)


Middle elements: 3 4




### Given the X numpy array, show the elements in reverse position

In [22]:
# your code goes here
X[::-1]

array([6, 5, 4, 3, 2, 1])



### Given the X numpy array, show the elements in an odd position

In [25]:
# your code goes here
x=np.array([1,2,3,4,5,6,7,8,9])
y=[]
for i in range(0,len(x),2):
  y.append(x[i])
y

[1, 3, 5, 7, 9]



### Given the X numpy matrix, show the first row elements

In [30]:
# your code goes here
b = np.array([[9,8,7,4],[6,5,4,6],[6,5,4,6]])
b[0,:]

array([9, 8, 7, 4])



### Given the X numpy matrix, show the last row elements

In [31]:
# your code goes here
b[-1,:]

array([6, 5, 4, 6])



### Given the X numpy matrix, show the first element on first row

In [32]:
# your code goes here
b[0,:][0]

9



### Given the X numpy matrix, show the last element on last row

In [33]:
# your code goes here
b[-1,:][-1]

6



### Given the X numpy matrix, show the last two elements on the last two rows

In [34]:
# your code goes here
b[1:,2:]

array([[4, 6],
       [4, 6]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [47]:
# your code goes here
a=np.array([1,2,3,4,5,6,7,8,9],dtype=float)
b=a.astype(int)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])



### Reverse the given numpy array (first element becomes last)

In [49]:
# your code goes here
b[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])



### Order (sort) the given numpy array

In [53]:
# your code goes here
a[::-1].sort()
a

array([9., 8., 7., 6., 5., 4., 3., 2., 1.])



### Given the X numpy array, set the fifth element equal to 1

In [56]:
# your code goes here
r=np.array([1,2,1,5,4,1,2,1,3,0,4,5,1])
sum=0
for i in range(len(r)):
  if r[i]==1:
     sum=sum+1
     if sum==5:
       print("l'element est ",i)


l'element est  12




### Given the X numpy array, change the 50 with a 40

In [58]:
# your code goes here
t=np.array([1,20,4,58,50,70,20,40])
for i in range(len(t)):
  if t[i]==50:
     t[i]=40
t

array([ 1, 20,  4, 58, 40, 70, 20, 40])


### Given the X numpy matrix, change the last row with all 1

In [83]:
# your code goes here
b = np.array([[9,8,7,4],[6,5,4,6],[6,5,4,6]])
b[-1,:]=1
b

array([[9, 8, 7, 4],
       [6, 5, 4, 6],
       [1, 1, 1, 1]])


### Given the X numpy matrix, change the last item on the last row with a 0

In [68]:
# your code goes here
b[-1,-1]=0
b


array([[9, 8, 7, 4],
       [6, 5, 4, 6],
       [1, 1, 1, 0]])


### Given the X numpy matrix, add 5 to every element

In [74]:
len(b)

3

In [84]:
for i in range(len(b)):
  b[i]=b[i]+5
b  

array([[14, 13, 12,  9],
       [11, 10,  9, 11],
       [ 6,  6,  6,  6]])


## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [85]:
# your code goes here
a = np.array([-4,5,1,2,3,5])
a<=1

array([ True, False,  True, False, False, False])


### Given the X numpy array, get the negative elements

In [ ]:
# your code goes here
a[a<0]

array([-4])


### Given the X numpy array, get numbers higher than 5

In [86]:
# your code goes here
a[5<a]

array([], dtype=int64)


### Given the X numpy array, get numbers higher than the elements mean

In [87]:
# your code goes here
a[a <a.mean()]

array([-4,  1])


### Given the X numpy array, get numbers equal to 2 or 10

In [89]:
# your code goes here
a [(a == 2) | (a == 10)]

array([2])


## Summary statistics

### Given the X numpy array, show the sum of its elements

In [92]:
# your code goes here
u=np.array([1,2,3,4])
u.sum()



10


### Given the X numpy array, show the mean value of its elements

In [ ]:
# your code goes here


In [ ]:
a

array([-4,  5,  1,  2,  3,  5])

In [95]:
a.mean()

2.0

### Given the X numpy array, show the max value of its elements

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



# Answer The following questions!

In [96]:
# your code goes here
import seaborn as sns

In [97]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [98]:
df = sns.load_dataset('titanic')

In [99]:
df[df.alone==True]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
2           1       3  female  26.0      0      0   7.9250        S   Third   
4           0       3    male  35.0      0      0   8.0500        S   Third   
5           0       3    male   NaN      0      0   8.4583        Q   Third   
6           0       1    male  54.0      0      0  51.8625        S   First   
11          1       1  female  58.0      0      0  26.5500        S   First   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
884         0       3    male  25.0      0      0   7.0500        S   Third   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
2    woman       False  NaN  Southampton   yes   True  
4      man        True  NaN  Southampton    no   True  
5      man        True  NaN   Queenstown    no   True  
6      man        True    E  Southampton    no   True  
11   woman       False    C  Southampton   yes   True  
..     ...         ...  ...          ...   ...    ...  
884    man        True  NaN  Southampton    no   True  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[537 rows x 15 columns]

# Average age of woman category.

In [ ]:
df[df.who=='woman'].age.mean()


32.0

## Average age of man category.

In [ ]:
df[df.alive == "True"].shape

(0, 15)

## The lowest age among alone woman.

survived  pclass   sex   age  ...  deck  embark_town  alive  alone
0           0       3  male  22.0  ...   NaN  Southampton     no  False
4           0       3  male  35.0  ...   NaN  Southampton     no   True
5           0       3  male   NaN  ...   NaN   Queenstown     no   True
6           0       1  male  54.0  ...     E  Southampton     no   True
12          0       3  male  20.0  ...   NaN  Southampton     no   True
..        ...     ...   ...   ...  ...   ...          ...    ...    ...
883         0       2  male  28.0  ...   NaN  Southampton     no   True
884         0       3  male  25.0  ...   NaN  Southampton     no   True
886         0       2  male  27.0  ...   NaN  Southampton     no   True
889         1       1  male  26.0  ...     C    Cherbourg    yes   True
890         0       3  male  32.0  ...   NaN   Queenstown     no   True

[537 rows x 15 columns]

. 